### ISSUE TITLE
document is not defined when using next js

### ISSUE THREAD

**Issue by efikuta** [michelecocuccio/simple-react-lightbox#21]
because of the ssr you need to check: "undefined" != typeof document
 before use "document."

please fix it because i want to use it

**Comment by michelecocuccio** [comment]
@efikuta sorry but for now it doesn't support server side rendering. I will try to do my best add support for it. Is there error showing when you run NextJS localy?

**Comment by parondeau** [comment]
I just ran across this myself. Here is the full stacktrace of the error

```
ReferenceError: document is not defined
    at /Users/parondeau/code/parondeau/node_modules/simple-react-lightbox/dist/index.js:12:30842
    at y (/Users/parondeau/code/parondeau/node_modules/simple-react-lightbox/dist/index.js:1:4302)
    at Object.<anonymous> (/Users/parondeau/code/parondeau/node_modules/simple-react-lightbox/dist/index.js:12:30459)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.simple-react-lightbox (/Users/parondeau/code/parondeau/.next/server/static/development/pages/_app.js:1638:18)
    at __webpack_require__ (/Users/parondeau/code/parondeau/.next/server/static/development/pages/_app.js:23:31)
    at Module../pages/_app.tsx (/Users/parondeau/code/parondeau/.next/server/static/development/pages/_app.js:1459:79)
    at __webpack_require__ (/Users/parondeau/code/parondeau/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/parondeau/code/parondeau/.next/server/static/development/pages/_app.js:1571:18)
    at __webpack_require__ (/Users/parondeau/code/parondeau/.next/server/static/development/pages/_app.js:23:31)
    at /Users/parondeau/code/parondeau/.next/server/static/development/pages/_app.js:91:18
```

**Comment by michelecocuccio** [comment]
Hello, thanks for this.
I am working to narrow down what it could be. I am using Emotion for styled components ad Emotion requires extra configuration on both Gatbsy and NextJS to use SSR. I am not even sure if it's that or something else. I am working hard to find the cause. I will update you when I have an updated on this. Unfortunately that error stack doesn't say much. If the cause is using Styled Components than that's going to be painful as I will have to remove all my styled components in order to use just inline CSS which I don't see it as an option to be honest.

**Comment by michelecocuccio** [comment]
@efikuta @parondeau version 2.6.3 should support NextJS and Gatsby. See the notes on the documentation.
